!obj:pylearn2.train.Train {
     dataset: &train !obj:utils.load_data {
        start: 0,
        stop: 250000
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [ !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h0',
                     dim: 2000,
                     sparse_init: 12
                 }, !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h1',
                     dim: 2000,
                     sparse_init: 12
                 }, !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h2',
                     dim: 2000,
                     sparse_init: 12
                 }, !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h3',
                     dim: 1000,
                     sparse_init: 12
                 }, !obj:pylearn2.models.mlp.Softmax {
                     layer_name: 'y',
                     n_classes: 2,
                     irange: 0.
                 }
                ],
        nvis: 30,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 5000,
        learning_rate: .00001,
        monitoring_dataset:
            {
                'train' : *train,
            },
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: .5
        },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.MonitorBased {
                    channel_name: "train_y_misclass",
                    prop_decrease: 0.,
                    N: 500
                },
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 500
                }
            ]
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'train_y_misclass',
             save_path: "mlp_best3.pkl"
        }, !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
            start: 1,
            saturate: 150,
            final_momentum: .99
        }
    ]
}
